[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

[functions."api/*"]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"

# Environment variables (configure these in Netlify dashboard)
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://gamb-marketing-digital.netlify.app/api"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://deploy-preview-branch--gamb-marketing-digital.netlify.app/api"
  NODE_ENV = "development"